apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: wave-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wave-manager-role
subjects:
- kind: ServiceAccount
  name: "default"
  namespace: "wave-demo"
- kind: ServiceAccount
  name: "default"
  namespace: "wave-system"
- kind: ServiceAccount
  name: "default"
  namespace: "default"
